/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppWriteRouteImport } from './routes/_app/write'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppArticlesRouteImport } from './routes/_app/articles'
import { Route as AppMeRouteRouteImport } from './routes/_app/me/route'
import { Route as AppMeIndexRouteImport } from './routes/_app/me/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersUsernameRouteImport } from './routes/_app/users.$username'
import { Route as AppMeFavoritesRouteImport } from './routes/_app/me/favorites'
import { Route as AppMeArticlesRouteImport } from './routes/_app/me/articles'
import { Route as AppMeSettingsRouteRouteImport } from './routes/_app/me/settings/route'
import { Route as AppMeSettingsIndexRouteImport } from './routes/_app/me/settings/index'
import { Route as AppMeSettingsSecurityRouteImport } from './routes/_app/me/settings/security'
import { Route as AppMeSettingsPublishingRouteImport } from './routes/_app/me/settings/publishing'
import { Route as AppMeSettingsNotificationsRouteImport } from './routes/_app/me/settings/notifications'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWriteRoute = AppWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesRoute = AppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeRouteRoute = AppMeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUsernameRoute = AppUsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeFavoritesRoute = AppMeFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppMeRouteRoute,
} as any)
const AppMeArticlesRoute = AppMeArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppMeRouteRoute,
} as any)
const AppMeSettingsRouteRoute = AppMeSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMeRouteRoute,
} as any)
const AppMeSettingsIndexRoute = AppMeSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeSettingsRouteRoute,
} as any)
const AppMeSettingsSecurityRoute = AppMeSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppMeSettingsRouteRoute,
} as any)
const AppMeSettingsPublishingRoute = AppMeSettingsPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AppMeSettingsRouteRoute,
} as any)
const AppMeSettingsNotificationsRoute =
  AppMeSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppMeSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/me': typeof AppMeRouteRouteWithChildren
  '/articles': typeof AppArticlesRoute
  '/search': typeof AppSearchRoute
  '/write': typeof AppWriteRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-up': typeof AuthSignUpRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/me/settings': typeof AppMeSettingsRouteRouteWithChildren
  '/me/articles': typeof AppMeArticlesRoute
  '/me/favorites': typeof AppMeFavoritesRoute
  '/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me/': typeof AppMeIndexRoute
  '/me/settings/notifications': typeof AppMeSettingsNotificationsRoute
  '/me/settings/publishing': typeof AppMeSettingsPublishingRoute
  '/me/settings/security': typeof AppMeSettingsSecurityRoute
  '/me/settings/': typeof AppMeSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof AppArticlesRoute
  '/search': typeof AppSearchRoute
  '/write': typeof AppWriteRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-up': typeof AuthSignUpRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/me/articles': typeof AppMeArticlesRoute
  '/me/favorites': typeof AppMeFavoritesRoute
  '/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me': typeof AppMeIndexRoute
  '/me/settings/notifications': typeof AppMeSettingsNotificationsRoute
  '/me/settings/publishing': typeof AppMeSettingsPublishingRoute
  '/me/settings/security': typeof AppMeSettingsSecurityRoute
  '/me/settings': typeof AppMeSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_app/me': typeof AppMeRouteRouteWithChildren
  '/_app/articles': typeof AppArticlesRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/write': typeof AppWriteRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/_app/me/settings': typeof AppMeSettingsRouteRouteWithChildren
  '/_app/me/articles': typeof AppMeArticlesRoute
  '/_app/me/favorites': typeof AppMeFavoritesRoute
  '/_app/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/me/': typeof AppMeIndexRoute
  '/_app/me/settings/notifications': typeof AppMeSettingsNotificationsRoute
  '/_app/me/settings/publishing': typeof AppMeSettingsPublishingRoute
  '/_app/me/settings/security': typeof AppMeSettingsSecurityRoute
  '/_app/me/settings/': typeof AppMeSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/me'
    | '/articles'
    | '/search'
    | '/write'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/articles/$slug'
    | '/me/settings'
    | '/me/articles'
    | '/me/favorites'
    | '/users/$username'
    | '/api/auth/$'
    | '/me/'
    | '/me/settings/notifications'
    | '/me/settings/publishing'
    | '/me/settings/security'
    | '/me/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/search'
    | '/write'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/articles/$slug'
    | '/me/articles'
    | '/me/favorites'
    | '/users/$username'
    | '/api/auth/$'
    | '/me'
    | '/me/settings/notifications'
    | '/me/settings/publishing'
    | '/me/settings/security'
    | '/me/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/about'
    | '/_app/me'
    | '/_app/articles'
    | '/_app/search'
    | '/_app/write'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/sign-up'
    | '/articles/$slug'
    | '/_app/me/settings'
    | '/_app/me/articles'
    | '/_app/me/favorites'
    | '/_app/users/$username'
    | '/api/auth/$'
    | '/_app/me/'
    | '/_app/me/settings/notifications'
    | '/_app/me/settings/publishing'
    | '/_app/me/settings/security'
    | '/_app/me/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/write': {
      id: '/_app/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof AppWriteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/articles': {
      id: '/_app/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AppArticlesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/me/': {
      id: '/_app/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppMeRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/$username': {
      id: '/_app/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AppUsersUsernameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/me/favorites': {
      id: '/_app/me/favorites'
      path: '/favorites'
      fullPath: '/me/favorites'
      preLoaderRoute: typeof AppMeFavoritesRouteImport
      parentRoute: typeof AppMeRouteRoute
    }
    '/_app/me/articles': {
      id: '/_app/me/articles'
      path: '/articles'
      fullPath: '/me/articles'
      preLoaderRoute: typeof AppMeArticlesRouteImport
      parentRoute: typeof AppMeRouteRoute
    }
    '/_app/me/settings': {
      id: '/_app/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof AppMeSettingsRouteRouteImport
      parentRoute: typeof AppMeRouteRoute
    }
    '/_app/me/settings/': {
      id: '/_app/me/settings/'
      path: '/'
      fullPath: '/me/settings/'
      preLoaderRoute: typeof AppMeSettingsIndexRouteImport
      parentRoute: typeof AppMeSettingsRouteRoute
    }
    '/_app/me/settings/security': {
      id: '/_app/me/settings/security'
      path: '/security'
      fullPath: '/me/settings/security'
      preLoaderRoute: typeof AppMeSettingsSecurityRouteImport
      parentRoute: typeof AppMeSettingsRouteRoute
    }
    '/_app/me/settings/publishing': {
      id: '/_app/me/settings/publishing'
      path: '/publishing'
      fullPath: '/me/settings/publishing'
      preLoaderRoute: typeof AppMeSettingsPublishingRouteImport
      parentRoute: typeof AppMeSettingsRouteRoute
    }
    '/_app/me/settings/notifications': {
      id: '/_app/me/settings/notifications'
      path: '/notifications'
      fullPath: '/me/settings/notifications'
      preLoaderRoute: typeof AppMeSettingsNotificationsRouteImport
      parentRoute: typeof AppMeSettingsRouteRoute
    }
  }
}

interface AppMeSettingsRouteRouteChildren {
  AppMeSettingsNotificationsRoute: typeof AppMeSettingsNotificationsRoute
  AppMeSettingsPublishingRoute: typeof AppMeSettingsPublishingRoute
  AppMeSettingsSecurityRoute: typeof AppMeSettingsSecurityRoute
  AppMeSettingsIndexRoute: typeof AppMeSettingsIndexRoute
}

const AppMeSettingsRouteRouteChildren: AppMeSettingsRouteRouteChildren = {
  AppMeSettingsNotificationsRoute: AppMeSettingsNotificationsRoute,
  AppMeSettingsPublishingRoute: AppMeSettingsPublishingRoute,
  AppMeSettingsSecurityRoute: AppMeSettingsSecurityRoute,
  AppMeSettingsIndexRoute: AppMeSettingsIndexRoute,
}

const AppMeSettingsRouteRouteWithChildren =
  AppMeSettingsRouteRoute._addFileChildren(AppMeSettingsRouteRouteChildren)

interface AppMeRouteRouteChildren {
  AppMeSettingsRouteRoute: typeof AppMeSettingsRouteRouteWithChildren
  AppMeArticlesRoute: typeof AppMeArticlesRoute
  AppMeFavoritesRoute: typeof AppMeFavoritesRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
}

const AppMeRouteRouteChildren: AppMeRouteRouteChildren = {
  AppMeSettingsRouteRoute: AppMeSettingsRouteRouteWithChildren,
  AppMeArticlesRoute: AppMeArticlesRoute,
  AppMeFavoritesRoute: AppMeFavoritesRoute,
  AppMeIndexRoute: AppMeIndexRoute,
}

const AppMeRouteRouteWithChildren = AppMeRouteRoute._addFileChildren(
  AppMeRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppMeRouteRoute: typeof AppMeRouteRouteWithChildren
  AppArticlesRoute: typeof AppArticlesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppWriteRoute: typeof AppWriteRoute
  AppUsersUsernameRoute: typeof AppUsersUsernameRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppMeRouteRoute: AppMeRouteRouteWithChildren,
  AppArticlesRoute: AppArticlesRoute,
  AppSearchRoute: AppSearchRoute,
  AppWriteRoute: AppWriteRoute,
  AppUsersUsernameRoute: AppUsersUsernameRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
